# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "libsy"
version = "0.1.0"
description = "Switchyard library crate"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = "0.1"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures = "0.3"
switchyard-translation = { path = "../switchyard-translation" }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
